export enum ExerciseType {
    CARDIO = "cardio",
    STRENGTH = "strength",
    FLEXIBILITY = "flexibility",
    HIIT = "hiit",
    PILATES = "pilates",
    YOGA = "yoga",
    CROSSFIT = "crossfit",
    CALISTHENICS = "calisthenics",
    AEROBICS = "aerobics",
    ENDURANCE = "endurance",
    POWERLIFTING = "powerlifting",
    OLYMPIC_WEIGHTLIFTING = "olympic_weightlifting",
    BODYBUILDING = "bodybuilding",
    FUNCTIONAL_TRAINING = "functional_training",
    REHABILITATION = "rehabilitation",
    SPORTS_SPECIFIC = "sports_specific",
    WARM_UP = "warm_up",
    COOL_DOWN = "cool_down"
}