export enum MuscleTarget {
  CHEST = 'chest',
  CORE = 'core',
  TRAPEZIUS = 'trapezius',
  LATS = 'lats',
  DELTOIDS = 'deltoids',
  TRICEPS = 'triceps',
  BICEPS = 'biceps',
  FOREARMS = 'forearms',
  QUADS = 'quads',
  HAMSTRINGS = 'hamstrings',
  GLUTES = 'glutes',
  ADDUCTORS = 'adductors',
  CALVES = 'calves',
  NECK = 'neck',
}

export const MuscleTargetLabels: Record<MuscleTarget, string> = {
  [MuscleTarget.CHEST]: 'Pecho',
  [MuscleTarget.CORE]: 'Core',
  [MuscleTarget.TRAPEZIUS]: 'Trapecio',
  [MuscleTarget.LATS]: 'Dorsales',
  [MuscleTarget.DELTOIDS]: 'Deltoides',
  [MuscleTarget.TRICEPS]: 'Tríceps',
  [MuscleTarget.BICEPS]: 'Bíceps',
  [MuscleTarget.FOREARMS]: 'Antebrazos',
  [MuscleTarget.QUADS]: 'Cuádriceps',
  [MuscleTarget.HAMSTRINGS]: 'Isquiotibiales',
  [MuscleTarget.GLUTES]: 'Glúteos',
  [MuscleTarget.ADDUCTORS]: 'Aductores',
  [MuscleTarget.CALVES]: 'Gemelos',
  [MuscleTarget.NECK]: 'Cuello',
};

export enum Equipment {
  BARBELL = 'barbell',
  DUMBBELL = 'dumbbell',
  MACHINE = 'machine',
  BODYWEIGHT = 'bodyweight',
  KETTLEBELL = 'kettlebell',
  RESISTANCE_BAND = 'resistance_band',
  CABLE = 'cable',
  OTHER = 'other',
}

export const EquipmentLabels: Record<Equipment, string> = {
  [Equipment.BARBELL]: 'Barra',
  [Equipment.DUMBBELL]: 'Mancuernas',
  [Equipment.MACHINE]: 'Máquina',
  [Equipment.BODYWEIGHT]: 'Peso Corporal',
  [Equipment.KETTLEBELL]: 'Pesa Rusa',
  [Equipment.RESISTANCE_BAND]: 'Banda de Resistencia',
  [Equipment.CABLE]: 'Cable',
  [Equipment.OTHER]: 'Otro',
};

export enum ExerciseType {
  CARDIO = 'cardio',
  STRENGTH = 'strength',
  FLEXIBILITY = 'flexibility',
  HIIT = 'hiit',
  PILATES = 'pilates',
  YOGA = 'yoga',
  CROSSFIT = 'crossfit',
  CALISTHENICS = 'calisthenics',
  AEROBICS = 'aerobics',
  ENDURANCE = 'endurance',
  POWERLIFTING = 'powerlifting',
  OLYMPIC_WEIGHTLIFTING = 'olympic_weightlifting',
  BODYBUILDING = 'bodybuilding',
  FUNCTIONAL_TRAINING = 'functional_training',
  REHABILITATION = 'rehabilitation',
  SPORTS_SPECIFIC = 'sports_specific',
  WARM_UP = 'warm_up',
  COOL_DOWN = 'cool_down',
}

export const ExerciseTypeLabels: Record<ExerciseType, string> = {
  [ExerciseType.CARDIO]: 'Cardio',
  [ExerciseType.STRENGTH]: 'Fuerza',
  [ExerciseType.FLEXIBILITY]: 'Flexibilidad',
  [ExerciseType.HIIT]: 'HIIT',
  [ExerciseType.PILATES]: 'Pilates',
  [ExerciseType.YOGA]: 'Yoga',
  [ExerciseType.CROSSFIT]: 'CrossFit',
  [ExerciseType.CALISTHENICS]: 'Calistenia',
  [ExerciseType.AEROBICS]: 'Aeróbica',
  [ExerciseType.ENDURANCE]: 'Resistencia',
  [ExerciseType.POWERLIFTING]: 'Powerlifting',
  [ExerciseType.OLYMPIC_WEIGHTLIFTING]: 'Levantamiento Olímpico',
  [ExerciseType.BODYBUILDING]: 'Fisicoculturismo',
  [ExerciseType.FUNCTIONAL_TRAINING]: 'Entrenamiento Funcional',
  [ExerciseType.REHABILITATION]: 'Rehabilitación',
  [ExerciseType.SPORTS_SPECIFIC]: 'Específico del Deporte',
  [ExerciseType.WARM_UP]: 'Calentamiento',
  [ExerciseType.COOL_DOWN]: 'Enfriamiento',
};

export enum SetType {
  WARM_UP = 'warm_up',
  EFFECTIVE = 'effective',
  PYRAMID = 'pyramid',
  REVERSE_PYRAMID = 'reverse_pyramid',
  SUPERSET = 'superset',
  BISET = 'biset',
  TRISET = 'triset',
  GIANT_SET = 'giant_set',
  DROP_SET = 'drop_set',
  REST_PAUSE = 'rest_pause',
  CLUSTER = 'cluster',
}

export const SetTypeLabels: Record<SetType, string> = {
  [SetType.WARM_UP]: 'Calentamiento',
  [SetType.EFFECTIVE]: 'Efectivo',
  [SetType.PYRAMID]: 'Pirámide',
  [SetType.REVERSE_PYRAMID]: 'Pirámide Inversa',
  [SetType.SUPERSET]: 'Superset',
  [SetType.BISET]: 'Biset',
  [SetType.TRISET]: 'Triset',
  [SetType.GIANT_SET]: 'Giant Set',
  [SetType.DROP_SET]: 'Drop Set',
  [SetType.REST_PAUSE]: 'Rest Pause',
  [SetType.CLUSTER]: 'Cluster',
};
